// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFile(arg1, arg2) {
  return window['go']['main']['App']['AcceptFile'](arg1, arg2);
}

export function AcceptHunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcceptHunk'](arg1, arg2, arg3);
}

export function ApplyTaskChanges(arg1) {
  return window['go']['main']['App']['ApplyTaskChanges'](arg1);
}

export function CheckProjectSetup(arg1) {
  return window['go']['main']['App']['CheckProjectSetup'](arg1);
}

export function CleanupAllWorkspaces() {
  return window['go']['main']['App']['CleanupAllWorkspaces']();
}

export function CleanupSessionWorkspaces(arg1) {
  return window['go']['main']['App']['CleanupSessionWorkspaces'](arg1);
}

export function CreateAgent(arg1) {
  return window['go']['main']['App']['CreateAgent'](arg1);
}

export function CreateMCPServer(arg1) {
  return window['go']['main']['App']['CreateMCPServer'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTeam(arg1) {
  return window['go']['main']['App']['CreateTeam'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetMCPInstallConfig(arg1) {
  return window['go']['main']['App']['GetMCPInstallConfig'](arg1);
}

export function GetMCPServer(arg1) {
  return window['go']['main']['App']['GetMCPServer'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionStats(arg1) {
  return window['go']['main']['App']['GetSessionStats'](arg1);
}

export function GetSessionStreamEvents(arg1) {
  return window['go']['main']['App']['GetSessionStreamEvents'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskDiff(arg1) {
  return window['go']['main']['App']['GetTaskDiff'](arg1);
}

export function GetTaskStreamEvents(arg1) {
  return window['go']['main']['App']['GetTaskStreamEvents'](arg1);
}

export function GetTeam(arg1) {
  return window['go']['main']['App']['GetTeam'](arg1);
}

export function ImprovePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImprovePrompt'](arg1, arg2, arg3);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListProjectFiles(arg1) {
  return window['go']['main']['App']['ListProjectFiles'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSessionsByProject(arg1) {
  return window['go']['main']['App']['ListSessionsByProject'](arg1);
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function PlanTasks(arg1, arg2) {
  return window['go']['main']['App']['PlanTasks'](arg1, arg2);
}

export function ReadProjectFile(arg1, arg2) {
  return window['go']['main']['App']['ReadProjectFile'](arg1, arg2);
}

export function RejectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RejectFile'](arg1, arg2, arg3);
}

export function RejectHunk(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RejectHunk'](arg1, arg2, arg3, arg4);
}

export function RejectTaskChanges(arg1) {
  return window['go']['main']['App']['RejectTaskChanges'](arg1);
}

export function RunProjectSetup(arg1, arg2) {
  return window['go']['main']['App']['RunProjectSetup'](arg1, arg2);
}

export function SaveWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWorkspaceFile'](arg1, arg2, arg3);
}

export function SearchMCPCatalog(arg1, arg2) {
  return window['go']['main']['App']['SearchMCPCatalog'](arg1, arg2);
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}

export function SendFollowUp(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFollowUp'](arg1, arg2, arg3);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function UpdateAgent(arg1) {
  return window['go']['main']['App']['UpdateAgent'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UpdateTeam(arg1) {
  return window['go']['main']['App']['UpdateTeam'](arg1);
}
