// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';
import {main} from '../models';
import {services} from '../models';
import {claude} from '../models';

export function AcceptFile(arg1:string,arg2:string):Promise<void>;

export function AcceptHunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ApplyTaskChanges(arg1:string):Promise<void>;

export function CleanupAllWorkspaces():Promise<void>;

export function CleanupSessionWorkspaces(arg1:string):Promise<void>;

export function CompleteSession(arg1:string):Promise<void>;

export function CreateAgent(arg1:models.Agent):Promise<models.Agent>;

export function CreateMCPServer(arg1:models.MCPServer):Promise<models.MCPServer>;

export function CreateProject(arg1:models.Project):Promise<models.Project>;

export function CreateSession(arg1:models.Session):Promise<models.Session>;

export function CreateTask(arg1:models.Task):Promise<models.Task>;

export function CreateTeam(arg1:models.Team):Promise<models.Team>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DeleteTeam(arg1:string):Promise<void>;

export function ExportMCPJson():Promise<string>;

export function GetAgent(arg1:string):Promise<models.Agent>;

export function GetConfig():Promise<config.Config>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetMCPInstallConfig(arg1:string):Promise<services.InstallConfig>;

export function GetMCPServer(arg1:string):Promise<models.MCPServer>;

export function GetSession(arg1:string):Promise<models.Session>;

export function GetSessionStats(arg1:string):Promise<main.SessionStats>;

export function GetSessionStreamEvents(arg1:string):Promise<Record<string, Array<claude.TaskStreamEvent>>>;

export function GetTask(arg1:string):Promise<models.Task>;

export function GetTaskDiff(arg1:string):Promise<services.DiffResult>;

export function GetTaskStreamEvents(arg1:string):Promise<Array<claude.TaskStreamEvent>>;

export function GetTeam(arg1:string):Promise<models.Team>;

export function ImportMCPFromClaude():Promise<string>;

export function ImprovePrompt(arg1:string,arg2:string,arg3:string):Promise<services.PromptImproveResult>;

export function ListAgents():Promise<Array<models.Agent>>;

export function ListMCPServers():Promise<Array<models.MCPServer>>;

export function ListProjectFiles(arg1:string):Promise<Array<string>>;

export function ListProjects():Promise<Array<models.Project>>;

export function ListSessions():Promise<Array<models.Session>>;

export function ListSessionsByProject(arg1:string):Promise<Array<models.Session>>;

export function ListTasks(arg1:string):Promise<Array<models.Task>>;

export function ListTeams():Promise<Array<models.Team>>;

export function ParseMCPJson(arg1:string):Promise<Array<services.MCPJsonImportEntry>>;

export function PlanTasks(arg1:string,arg2:string):Promise<services.PlanResult>;

export function ReadProjectFile(arg1:string,arg2:string):Promise<string>;

export function RejectFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RejectHunk(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function RejectTaskChanges(arg1:string):Promise<void>;

export function SaveWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchMCPCatalog(arg1:string,arg2:number):Promise<services.CatalogResponse>;

export function SeedExampleAgents():Promise<Array<models.Agent>>;

export function SelectProjectFolder():Promise<string>;

export function SendFollowUp(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function StopTask(arg1:string):Promise<void>;

export function SyncMCPFromJson(arg1:string):Promise<void>;

export function TestMCPServer(arg1:string,arg2:Array<string>,arg3:Record<string, string>):Promise<services.MCPHealthResult>;

export function UpdateAgent(arg1:models.Agent):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateMCPServer(arg1:models.MCPServer):Promise<void>;

export function UpdateProject(arg1:models.Project):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<void>;

export function UpdateTeam(arg1:models.Team):Promise<void>;
